# Setup: No TPM. All plugins managed by git submodule.
# How to use: soft link this file and .tmux/ directory to user home
unbind C-b
set -g prefix '`'
bind ` send-prefix
set -g mouse on
set-window-option -g mode-keys vi

# Intuitive split keys
bind | split-window -h
bind - split-window -v

bind t select-layout tiled  # overrides t=time

# -- fzf --

# prefix + enter: commands
# if select a command from fzf, will use it
# if manually type a command, will also use it
# this is implemented as choosing the longest line in the fzf output
bind-key -N "fzf commands" Enter display-popup -w 80% -h 80% -E 'cmd=$(tmux list-commands | cut -d " " -f1 | fzf --preview "tmux list-commands {} 2>/dev/null || true" --preview-window=right:60%:wrap --print-query | awk "length(\$0) > max {max = length(\$0); line = \$0} END {print line}"); [ -n "$cmd" ] && tmux $cmd'
# prefix + ?: keys
bind-key -N "fzf keybindings" ? display-popup -w 80% -h 80% -E 'tmux list-keys -aN | fzf'

# -- Plugins --

# yank
run-shell ~/.tmux/plugins/tmux-yank/yank.tmux

# dotbar (status line)
set -g status-left-length 40
set -g @tmux-dotbar-bg "#4D55CC"
set -g @tmux-dotbar-fg "#0B0E14"
set -g @tmux-dotbar-fg-session "#FFC85C"
set -g @tmux-dotbar-fg-prefix "#FFC85C"
set -g @tmux-dotbar-bold-current-window true
set -g @tmux-dotbar-bold-session true
set -g @tmux-dotbar-bold-status-right false
set -g @tmux-dotbar-session-text " [#S] "
set -g @tmux-dotbar-session-position left
set -g @tmux-dotbar-window-status-format " #I:#W "
set -g @tmux-dotbar-ssh-icon-only true
set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text '#{?#{==:#{pane_current_command},ssh},,#(gitmux "#{pane_current_path}")}'  # requires gitmux
run ~/.tmux/plugins/tmux-dotbar/dotbar.tmux

# autoreload
set-environment -g ENTR_FOLLOW_SYMLINK 1
run-shell ~/.tmux/plugins/tmux-autoreload/tmux-autoreload.tmux

# resurrect
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

