unbind C-b
set -g prefix '`'
bind ` send-prefix
set -g mouse on
set-window-option -g mode-keys vi

# vertical and horizontal split (vim-like)
bind t select-layout tiled # overrides t=time
# TODO: clipboard
